[package]
name = "mxrxtx"
version = "0.1.0"
authors = ["Erkki Seppälä <erkki.seppala@vincit.fi>"]
edition = "2018"

[dependencies]
anyhow = "1.0.44"
atomicwrites = "0.3.0"
clap = "3.0.0" #_FOR_WINDOWS clap = { version = "3.0.0-beta.2", features = ["std", "suggestions", "derive", "cargo"], default-features = false, optional = false }
directories-next = "2.0.0"
log = "0.4.14"
log4rs = "1.0.0"
matrix-sdk = { version="0.6.2", features = ["sled"] }
matrix-sdk-sled = "0.2.0"
matrix_uri = "0.1.0"
regex = "1.5.4"
ruma = "0.7.4"
ruma-client-api = "0.15.3"
ruma-common = "0.10.5"
ruma-events = "0.26.1"
ruma-identifiers = "0.22.1"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
termion = "1.5.6"
thiserror = "1.0.29"
tokio = "1.12.0"
toml = "0.5.8"
url = "2.2.2"
uuid = "1.2.2"
webrtc = { git = "https://github.com/webrtc-rs/webrtc", tag = "v0.1.0-beta.0.0.15" }

[build-dependencies]
vergen = "3"
