#!/bin/bash
is_repo_clean() {
    !(git status -uno --porcelain | grep -q .)
}
if ! is_repo_clean; then
    echo
    echo REPOSITORY IS NOT CLEAN, STOPPING
    echo
    git status -uno
    exit 1
fi
version="$1"
if [ -z "$version" ]; then
    echo usage: scripts/tag v1.2.3
    exit 1
fi
set -e
set -x
scripts/update-cargo-version.sh "$(sed 's/^.//' <<< $version)"
cargo update -p mxrxtx
cargo clippy
cargo test
# the change may have already done, so this can be skipped
git commit -m "Bumped version to $version" Cargo.toml Cargo.lock || true
previous=$((echo $version; git tag) | sort -Vr | grep -F -A1 -- "$version" | tail -1)
git tag --force --annotate --cleanup=whitespace --edit \
    --message "$(echo $version; echo; git shortlog "$previous.." | sed 's/^ *//')" \
    "$version"
