on:
  push:
    tags:
      - 'v*'

name: tag
jobs:
  start:
    name: Create release
    permissions:
      issues: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    outputs:
      git_describe: ${{ steps.git_describe.outputs.git_describe }}
    steps:
      # https://github.com/actions/create-release
      - uses: actions/checkout@v2
        with:
          submodules: true
      # https://stackoverflow.com/a/58178121
      - name: Set release information
        id: git_describe
        run: echo ::set-output name=git_describe::"$(git describe --tags)"
      # https://stackoverflow.com/a/58178121
      - name: Build started notification
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "mxrxtx release ${{ steps.git_describe.outputs.git_describe }} build started. [Progress.](https://github.com/eras/mxrxtx/actions/runs/${{github.run_id}})"
          server: ${{ secrets.MATRIX_SERVER }}
      - name: Cancel if no tag
        if: ${{ steps.git_describe.outputs.git_describe == '' }}
        run: false
  unix:
    name: mxrxtx
    needs: start
    permissions:
      issues: write
      pull-requests: write
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
        # macos-latest crashes
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install build deps
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install git
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: build
        env:
          GIT_DESCRIBE: ${{ needs.start.outputs.git_describe }}
        run: 'cargo build --release --locked'
      - run: strip target/release/mxrxtx
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
      - run: "gzip -9 < target/release/mxrxtx > mxrxtx.gz"
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
      - uses: actions/upload-artifact@v2
        with:
          path: mxrxtx.gz
          name: mxrxtx-${{ runner.os }}.gz
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
  windows:
    name: mxrxtx
    needs: start
    permissions:
      issues: write
      pull-requests: write
      contents: write
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # https://stackoverflow.com/a/58178121
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: build
        env:
          GIT_DESCRIBE: ${{ needs.start.outputs.git_describe }}
        run: 'cargo build --release'
      - run: 'tar.exe -a -c -f mxrxtx.zip -C target/release mxrxtx.exe'
      - uses: actions/upload-artifact@v2
        with:
          path: mxrxtx.zip
          name: mxrxtx-${{ runner.os }}.zip
  publish:
    runs-on: ubuntu-latest
    needs: [start, unix, windows]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: actions/download-artifact@v3
        with:
          path: .
      - run: 'ls -la'
      - name: Publish release
        uses: eloquent/github-release-action@v3
        with:
          # Note the "|" character: this is a multi-line string
          assets: |
            - path: mxrxtx-Windows.zip
              name: mxrxtx-${{ needs.start.outputs.git_describe }}-Windows.zip
              label: Windows binary
            - path: mxrxtx-Linux.gz
              name: mxrxtx-${{ needs.start.outputs.git_describe }}-Linux.gz
              label: Linux binary
  notify_end_success:
    runs-on: ubuntu-latest
    needs: [start, publish]
    if: ${{ success() }}
    steps:
      - name: Build succeeded notification
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "mxrxtx release ${{ needs.start.outputs.git_describe }} build complete. [Logs.](https://github.com/eras/mxrxtx/actions/runs/${{github.run_id}})"
          server: ${{ secrets.MATRIX_SERVER }}
  notify_end_failed:
    runs-on: ubuntu-latest
    needs: [start, publish]
    if: ${{ failure() }}
    steps:
      - name: Build failed notification
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "mxrxtx release ${{ needs.start.outputs.git_describe }} build failed. [Logs.](https://github.com/eras/mxrxtx/actions/runs/${{github.run_id}})"
          server: ${{ secrets.MATRIX_SERVER }}
